### ISSUE TITLE
Not supported server-side rendering (SSR)

### ISSUE THREAD

**Issue by kuleyu** [inotom/vue-go-top#5]
## Issue details
used `@inotom/vue-go-top` in a gridsome project, it works normal in develop environment, but causes `window is not defined` error when use `gridsome build` to build.

Had found the reason is that "`gridsome build` uses server-side rendering (SSR) to create a fully rendered page",  and by referring the gridsome doc [here: Add External Scripts - without-ssr-support](https://gridsome.org/docs/assets-scripts/#without-ssr-support), i used the following code:

```html
<template>
  <div class="layout" :class="{ 'sticky-header': $route.path === '/' }">
    <Navbar />
    <!-- <Header /> -->
    <slot/>
    <ClientOnly>
    <go-top :has-outline="false" :size="50" :max-width="320" bg-color="#38b2ac"/>
    </ClientOnly>
    <Footer />
  </div>
</template>

<script>
import Navbar from "@/components/Navbar"
// import GoTop from '@inotom/vue-go-top'
import Footer from "@/components/Footer"

export default {
  components: {
    Navbar,
    Footer,
    GoTop: () =>
        import ('@inotom/vue-go-top')
        .then(m => m.GoTop)
        .catch()
  }
}
</script>
```
but it now doesn't work even in develop environment. Could anybody help here?

**Comment by inotom** [comment]
Using `process.isClient` to load `GoTop` only on browser will eliminate the error.

```js
const GoTop = process.isClient ? require('@inotom/vue-go-top').default : null;

export default {
  components: {
    Navbar,
    Footer,
    GoTop,
  }
}
```

[Client API - Gridsome](https://gridsome.org/docs/client-api/#isclient)

**Comment by kuleyu** [comment]
> Using `process.isClient` to load `GoTop` only on browser will eliminate the error.
> 
> ```js
> const GoTop = process.isClient ? require('@inotom/vue-go-top').default : null;
> 
> export default {
>   components: {
>     Navbar,
>     Footer,
>     GoTop,
>   }
> }
> ```
> 
> [Client API - Gridsome](https://gridsome.org/docs/client-api/#isclient)

---
Woo, Thanks @inotom !☺ It had been solved by this way.
