### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by ijelliti** [inotom/vue-go-top#8]
hi folks,
I tried to install the vue-go-top package in my VueJS (nuxt) project using the SFC way. but I always face 
**`referenceError: window is not defined`**
I also tried to import it in with **plugins** arrays in the **nuxt.config.js** file with options `ssr: false`
I face another error for component not registred
`[Vue warn]: Unknown custom element: <go-top> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
can any help in this

**Comment by inotom** [comment]
Using `process.client` to import `GoTop` only on the client-side will eliminate the error.

```js
const GoTop = process.client ? require('@inotom/vue-go-top').default : null;

export default {
  components: {
    GoTop,
  },
}
```
[window or document undefined - NuxtJS](https://nuxtjs.org/faq/window-document-undefined/)

**Comment by ijelliti** [comment]
@inotom thanks that resolve my issue
